<a href="https://colab.research.google.com/github/kipdallaris/Python451Dallaris/blob/main/dallarishw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [ ]:
## Enter answer here.
def age_in_seconds(age):
  seconds_per_year = 365.25 * 24 * 60 * 60
  return age * seconds_per_year
age = int(input("Please enter your age: "))
seconds = age_in_seconds(age)
if seconds > 1_000_000_000:
    print("You are more than a billion seconds old.")
else:
    print("You are less than a billion seconds old.")
print(f"You are {seconds} seconds old.")



Please enter your age: 22
You are less than a billion seconds old.
You are 694267200.0 seconds old.


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [ ]:
## Enter answer here.

names = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']
for name in names:
  print(f"Good morning, {name}")

Good morning, Ashley
Good morning, Brianna
Good morning, Chetan
Good morning, David
Good morning, Eoin
Good morning, Francois
Good morning, Gemma
Good morning, Hameed
Good morning, Ishaan
Good morning, Joanna


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [ ]:
## Enter answer here.
numbers = [12, 34, 55, 18, 60, 23, 44, 71, 82, 39, 48, 57, 76, 13, 94]
for number in numbers:
    if number % 2 == 0:
        print(number)


12
34
18
60
44
82
48
76
94


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [ ]:
## Enter answer here.

nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2
numbers = [1.5, 2, -1, 3.5, -2.5, 0, 8, 7, -3, 10]
squared_numbers = [number ** 2 for number in numbers]
print("Squared numbers using list comprehension:")
for squared_number in squared_numbers:
    print(squared_number)

[0, 1.5625, 251.53959999999998, 625]
Squared numbers using list comprehension:
2.25
4
1
12.25
6.25
0
64
49
9
100


### Q5. Write a program to print a year if it is a leap year.

In [ ]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

1900
1900 is a leap year


In [ ]:
def is_leap_year(year):
    if (year % 400 == 0) or (year % 100 != 0 and year % 4 == 0):
        return True
    else:
        return False
year = int(input("Enter a year to check if it's a leap year: "))
if is_leap_year(year):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

Enter a year to check if it's a leap year: 2025
2025 is not a leap year.


### Q6. Use list comprensions to print all names in a list in upper case.

In [ ]:
names = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']
upper_case_names = [name.upper() for name in names]
for name in upper_case_names:
    print(name)

ASHLEY
BRIANNA
CHETAN
DAVID
EOIN
FRANCOIS
GEMMA
HAMEED
ISHAAN
JOANNA


### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [ ]:
# Write your answer here. Feel free to break your answer into different blocks of code rather than using just this one cell. Label your answer neatly.
import numpy as np
original = np.random.uniform(low=0, high=100, size=100)
largest_number = np.max(original)
smallest_number = np.min(original)
median_value = np.median(original)
standard_deviation = np.std(original)
print("Original Array Statistics:")
print(f"Largest number: {largest_number}")
print(f"Smallest number: {smallest_number}")
print(f"Median: {median_value}")
print(f"Standard deviation: {standard_deviation}")



Original Array Statistics:
Largest number: 99.38404456186835
Smallest number: 2.2314342068735615
Median: 54.96083107708378
Standard deviation: 29.038350115085777


In [ ]:
orig_sqrt = np.sqrt(original)
print("\nSquare Roots of Original Array:")
print(orig_sqrt)


Square Roots of Original Array:
[6.53383057 8.20456078 8.23022787 9.88435966 7.96438736 6.91377666
 4.4745166  9.51882063 7.00288806 7.09375694 7.73483135 9.8103883
 4.50035631 1.8856562  7.59711611 6.18039896 5.4706221  8.96592533
 5.83079967 6.92074096 9.87311324 3.20020886 8.71599489 8.39857187
 5.04259744 7.81388188 1.49379858 3.66338388 7.75319825 8.46856091
 9.32638715 2.13631426 9.11125933 9.96915466 8.35239627 5.35160627
 7.98457859 9.37223277 9.01028655 5.47970446 4.26121262 9.08557678
 7.04121643 4.28502401 7.52410339 9.45356075 7.35496146 7.99991066
 2.0968406  6.46114777 6.44113233 7.99821238 9.17288898 9.77068173
 6.70770105 5.47616375 9.02835321 8.18147241 6.44206538 9.57248718
 8.64917806 6.44710118 2.42582884 8.87031151 8.5573901  9.29946034
 5.77125995 6.09650147 9.39528194 4.25370101 9.96433441 1.84544603
 7.81530468 3.09403137 7.92736146 7.35199958 9.84906897 5.60641339
 9.60918282 9.11616045 6.90381757 9.9426039  6.80403498 3.46935422
 3.02314878 7.39956207 2.10146

In [ ]:
import numpy as np
original = np.random.uniform(low=0, high=100, size=100)
mat_array = original.reshape(20, 5)
print("2D Array (20 rows x 5 columns):")
print(mat_array)

2D Array (20 rows x 5 columns):
[[ 5.40891285 10.14875592  1.11853614  4.11292104 76.97096244]
 [43.42151306 70.75367211 14.46325514 14.09673015 29.51405311]
 [90.07974674 30.93600523 28.00789828 27.26246118 98.54587267]
 [86.75491133  3.42996021 77.20960357 89.06412787 63.57787779]
 [88.92768417 26.28978671 64.35188479 99.58055209  4.29057115]
 [46.67420662 52.00390947 74.68163621 27.55371656 35.30262556]
 [77.21108018 89.7081078  76.47777957 72.94257914 43.18948986]
 [32.80846671 99.9770042  95.91089487 51.81011044 91.65585691]
 [19.05289008 94.36169602 79.55105886 32.38724319 11.10036591]
 [52.92874557 46.87696315 61.85164445 69.45410301 58.34617424]
 [56.81290477 66.00573548  9.48544406 90.35529392 72.86081286]
 [81.23335737 80.32354755 24.51710649 40.56527958 72.8542474 ]
 [96.89817609 33.61430173 66.56500466 11.02842662 69.68158983]
 [55.9592459  77.74344936 30.26286171  4.88739377 48.87815172]
 [51.46452876 78.62162019 88.29879416 86.99899386 73.17247838]
 [27.87953621 45.938233

In [ ]:
column_means = np.mean(mat_array, axis=0)
print("\nMean of each column in mat_array:")
print(column_means)


Mean of each column in mat_array:
[57.72575816 60.55672055 52.34979932 45.02828919 61.37213272]


In [ ]:
row_sums = np.sum(mat_array, axis=1)
print("\nSum of each row in mat_array:")
print(row_sums)


Sum of each row in mat_array:
[ 97.76008839 172.24922357 274.8319841  320.03648076 283.44047891
 236.21609442 359.52903655 372.16233313 236.45325405 289.45763043
 295.52019109 299.4935384  277.78749893 217.73110246 378.55641536
 170.01675793 269.57838921 422.9964226  278.42964601 288.40743258]


In [ ]:
transpose_array = mat_array.T
print("\nTranspose of mat_array (dimensions):", transpose_array.shape)
transpose_column_means = np.mean(transpose_array, axis=0)
print("Mean of each column in transpose_array:")
print(transpose_column_means)
transpose_row_sums = np.sum(transpose_array, axis=1)
print("Sum of each row in transpose_array:")
print(transpose_row_sums)



Transpose of mat_array (dimensions): (5, 20)
Mean of each column in transpose_array:
[19.55201768 34.44984471 54.96639682 64.00729615 56.68809578 47.24321888
 71.90580731 74.43246663 47.29065081 57.89152609 59.10403822 59.89870768
 55.55749979 43.54622049 75.71128307 34.00335159 53.91567784 84.59928452
 55.6859292  57.68148652]
Sum of each row in transpose_array:
[1154.51516327 1211.13441095 1046.99598633  900.56578381 1227.44265449]


In [ ]:
import numpy as np
original = np.random.uniform(low=0, high=100, size=100)
mat_array = original.reshape(20, 5)
slice_a = mat_array[2:10, :]
print("Array with 3rd to 10th rows and all columns:")
print(slice_a)

Array with 3rd to 10th rows and all columns:
[[ 3.96546495 35.17134156  8.80501457 84.70978221  3.79175139]
 [39.09456071 98.56976545 54.27021325 55.53103827 22.28915009]
 [ 4.09374389 14.83815574  3.39486358 28.67242866 50.91999654]
 [ 3.70473536 88.0151201  92.88580175 52.18168378 67.8522084 ]
 [47.0336525  49.21988418 39.93868628 20.08178134 33.82054993]
 [31.56737296 15.53545221 15.19992076 93.965623    7.82106496]
 [91.04398936 36.76204759 50.1501216  24.05053703 98.41774735]
 [33.14889016 43.59845083 60.46252884 70.15814882  6.80389751]]


In [ ]:
slice_b = mat_array[-5:, -2:]
print("\nArray with the last 5 rows and last 2 columns:")
print(slice_b)
print("Dimensions of this array:", slice_b.shape)


Array with the last 5 rows and last 2 columns:
[[66.03470945 91.04572369]
 [64.78870081 10.40389568]
 [ 7.01708218 30.06581915]
 [ 0.30014092 53.31326414]
 [44.52655074 64.47612112]]
Dimensions of this array: (5, 2)


In [ ]:
transpose_array = mat_array.T
slice_c = transpose_array[:3, :]
print("\nArray with the first 3 rows and all columns of transpose_array:")
print(slice_c)


Array with the first 3 rows and all columns of transpose_array:
[[35.66101933 48.17290193  3.96546495 39.09456071  4.09374389  3.70473536
  47.0336525  31.56737296 91.04398936 33.14889016 32.47921324 74.49725025
  52.21433651 87.94292955 76.35969954 91.21042639 19.10553999 61.69729811
  60.90375263 69.4472905 ]
 [98.73429227 25.34826592 35.17134156 98.56976545 14.83815574 88.0151201
  49.21988418 15.53545221 36.76204759 43.59845083 82.06317539 85.31788911
  79.70169017 87.80928524 79.43356373  1.39823757  3.68801032 42.12718088
  26.11172077 21.17043178]
 [ 1.72985161 89.27567433  8.80501457 54.27021325  3.39486358 92.88580175
  39.93868628 15.19992076 50.1501216  60.46252884 47.39121664 61.56586952
  93.38710733 89.36745711  0.46481846 29.13076351 94.188876    5.650031
  96.81150055 14.10955171]]


### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [ ]:
# Write your answer here.
import numpy as np
diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']
age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]
def decide_menu(diet, age):
    if diet in ['vegan', 'vegetarian']:
        if age >= 21:
            return 'veg. fried rice with whiskey'
        else:
            return 'veg. fried rice with mocktail'
    elif diet == 'pescetarian':
        if age >= 21:
            return 'fish and white wine'
        else:
            return 'fish with mocktail'
    elif diet in ['keto', 'omnivore']:
        if age >= 21:
            return 'steak and red wine'
        else:
            return 'steak with mocktail'
menu = [decide_menu(diet[i], age[i]) for i in range(len(diet))]
for i, item in enumerate(menu):
    print(f"Guest {i + 1} ({diet[i]}, age {age[i]}): {item}")


Guest 1 (vegetarian, age 21): veg. fried rice with whiskey
Guest 2 (pescetarian, age 20): fish with mocktail
Guest 3 (vegetarian, age 19): veg. fried rice with mocktail
Guest 4 (omnivore, age 25): steak and red wine
Guest 5 (pescetarian, age 27): fish and white wine
Guest 6 (keto, age 18): steak with mocktail
Guest 7 (keto, age 23): steak and red wine
Guest 8 (vegan, age 25): veg. fried rice with whiskey
Guest 9 (omnivore, age 19): steak with mocktail
Guest 10 (omnivore, age 22): steak and red wine
Guest 11 (vegan, age 20): veg. fried rice with mocktail
Guest 12 (omnivore, age 20): steak with mocktail
Guest 13 (keto, age 23): steak and red wine
Guest 14 (vegetarian, age 21): veg. fried rice with whiskey
Guest 15 (vegan, age 24): veg. fried rice with whiskey
